"""Add SavedPost database model for saved posts

Revision ID: 55003885b0e9
Revises: 3eb7317d685b
Create Date: 2025-07-24 22:43:24.125079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55003885b0e9'
down_revision = '3eb7317d685b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_posts')
    # ### end Alembic commands ###
