"""Add ON DELETE CASCADE to post_id in comments and likes

Revision ID: 775eb201800a
Revises: c5b2e32c5f95
Create Date: 2025-06-03 23:59:53.721104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775eb201800a'
down_revision = 'c5b2e32c5f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_post_id_fkey'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
