"""Add ondelete property to SavedPost model

Revision ID: c5ef077a47b1
Revises: 55003885b0e9
Create Date: 2025-07-31 15:35:37.282568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ef077a47b1'
down_revision = '55003885b0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_post', ['user_id', 'post_id'])
        batch_op.drop_constraint(batch_op.f('saved_posts_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('saved_posts_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('saved_posts_post_id_fkey'), 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('saved_posts_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('unique_user_post', type_='unique')

    # ### end Alembic commands ###
