"""Add unique constraint for title and content

Revision ID: d91674c25283
Revises: 6693f803b0dc
Create Date: 2025-06-03 01:13:12.205056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91674c25283'
down_revision = '6693f803b0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_title_content', ['title', 'content'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('uix_title_content', type_='unique')

    # ### end Alembic commands ###
